### ISSUE TITLE
NetServer/ClientConfiguration sealed

### ISSUE THREAD

**Issue by johmarjac** [Eastrall/Sylver.Network#1]
Hi,

I just noticed the NetServerConfiguration class is sealed. Looking at the Sample Program.cs which sets up a TCP Server and looking at the instantiation of the Configuration I came up with an idea, that you could simply use Json to store the Configuration on the disk. It would work no offense. Then I thought more about that and was thinking about storing more App-Specific configuration in the NetServerConfiguration. I mean it is necessary to create a class derived from NetServer. In that derived class is the App-Specific code. It would be good if the NetserverConfiguration can also be derived with further properties on it to be able to serialize them to Json.

Do you know what I mean ? :D

**Comment by johmarjac** [comment]
That is exactly what I want but it will not work since `NetServerConfiguration` is `sealed`

**Comment by Eastrall** [comment]
You are correct. I might be a good idea to make the `NetServerConfiguration` class not sealed, this will open the possibilities for loading custom configurations.

Adding to roadmap, thank you for the suggestion!

**Comment by Eastrall** [comment]
PR #2 merged. Closing issue.

Thank you for the contribution!
